server:
  servlet:
    session:
      cookie:
        name: m_a_s_i_dev

spring:
  datasource:
    url: jdbc:mysql://mysql.mysql:3306/memocode_authorization_server_dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.dev.memocode.dev"
      client:
        registration:
          kakao:
            redirect-uri: "https://auth.dev.memocode.dev/login/oauth2/code/kakao"
      authorizationserver:
        client:
          public-client:
            token:
              access-token-time-to-live: 30d
            registration:
              redirect-uris:
                - "http://localhost:5173"
                - "https://dev.memocode.dev"
              post-logout-redirect-uris:
                - "http://localhost:5173"
                - "https://dev.memocode.dev"
  kafka:
    topic:
      users: "memocode-dev.outbox.event.USER"
    producer:
      bootstrap-servers: redpanda-0.redpanda.redpanda:9093
    consumer:
      bootstrap-servers: redpanda-0.redpanda.redpanda:9093

custom:
  front:
    domain: "http://localhost:5173"
    domain2: "https://dev.memocode.dev"

# logging
logging:
  level:
    org.springframework.security: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true