server:
  servlet:
    session:
      cookie:
        name: m_a_s_i_prod

spring:
  datasource:
    url: jdbc:mysql://mysql.mysql:3306/memocode_authorization_server_prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.memocode.dev"
      client:
        registration:
          kakao:
            redirect-uri: "https://auth.memocode.dev/login/oauth2/code/kakao"
      authorizationserver:
        client:
          public-client:
            registration:
              redirect-uris:
                - "https://memocode.dev"
              post-logout-redirect-uris:
                - "https://memocode.dev"
  kafka:
    topic:
      users: "memocode-prod.outbox.event.USER"
    producer:
      bootstrap-servers: redpanda-0.redpanda.redpanda:9093
    consumer:
      bootstrap-servers: redpanda-0.redpanda.redpanda:9093

custom:
  front:
    domain: "https://memocode.dev"
    domain2: "https://memocode.dev"