spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prod-server:32000/memocode_authorization_server_dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000"
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:9000/login/oauth2/code/kakao"
      authorizationserver:
        client:
          public-client:
            token:
              access-token-time-to-live: 30d
            registration:
              redirect-uris:
                - "http://localhost:5173"
              post-logout-redirect-uris:
                - "http://localhost:5173"
  kafka:
    topic:
      users: "memocode-dev.outbox.event.USER"
    security:
      protocol: SASL_SSL
    ssl:
      trust-store-location: classpath:/kafka/client-truststore.jks
      trust-store-password: 123456
    producer:
      bootstrap-servers: prod-server:31092
      properties:
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: ${SASL_JAAS_CONFIG:org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="1234";}
    consumer:
      bootstrap-servers: prod-server:31092
      properties:
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: ${SASL_JAAS_CONFIG:org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="1234";}

custom:
  front:
    domain: "http://localhost:5173"
    domain2: "http://localhost:5173"

# logging
logging:
  level:
    org.springframework.security: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true