server:
  servlet:
    session:
      cookie:
        name: m_a_s_i_prod

spring:
  datasource:
    url: jdbc:mysql://mysql.mysql:3306/memocode_authorization_server_prod
    username: ENC(/lWpzpR2gCPO/kb+m7DAECV/zf/7rQOqdch14ZdfPZO67+SsAu9YuLh1OixtcPhs)
    password: ENC(GUhqdgL8r/jbEWozq6kPbBuh1LXutdVD5TB0UvcADVo7PM5SV0ONuR3xaSvT44zM)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.memocode.dev"
      client:
        registration:
          kakao:
            client-id: ENC(ftvThDShJ2fF1yUDfa+Q/gDrXsyz1o5QtMDFzV0Q8E8wBXpkPnQgMh8k55jBXeTujfRSQOe/+nvy38sCZX4zVF5TSoRw3P7FVeL0cVwswA4=)
            redirect-uri: "https://auth.memocode.dev/login/oauth2/code/kakao"
      authorizationserver:
        client:
          public-client:
            registration:
              client-id: "7d05e434-8eaf-422d-b69c-627f0812ad6b"
              client-secret: "{noop}56f0bba9-f1de-46a5-978e-ee5aa6300c76"
              redirect-uris:
                - "https://memocode.dev"
              post-logout-redirect-uris:
                - "https://memocode.dev"
          authorization-server:
            registration:
              client-id: "38b17f48-075e-4881-a1a0-76604cb12888"
              client-secret: "{noop}27a7f252-1717-42a2-9f49-c4eb24bbbdb8"
          user-server:
            registration:
              client-id: "1b0f0816-a658-4c33-928c-2d64049560f4"
              client-secret: "{noop}1311719f-9ff4-4ff4-957e-4088128514ee"

custom:
  front:
    domain: "https://memocode.dev"

jasypt:
  encryptor:
    password: "${JASYPT_ENCRYPTOR_PASSWORD}"